stages:
  ingest:
    cmd: python src/ingest.py
    deps:
      - src/ingest.py
      - data/raw/creditcard.csv
      - params.yaml
    params:
      - data.raw_path
      - data.time_split_train
      - data.time_split_test
    outs:
      - data/processed/train.parquet
      - data/processed/test.parquet
      - data/processed/production_sim.parquet

preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - data/processed/train.parquet
      - data/processed/test.parquet
      - data/processed/production_sim.parquet
      - params.yaml
    params:
      - model.random_state
    outs:
      - data/processed/X_train.npy
      - data/processed/y_train.npy
      - data/processed/X_test.npy
      - data/processed/y_test.npy
      - data/processed/X_prod.npy
      - data/processed/y_prod.npy
      - data/processed/preprocessor.joblib